Repository decrn/localsurvey, pull requests merged in 2019-01, with the labels that each got.

#10 Add travis-ci
  .travis.yml
Labels: Devops

#11 Add build step to travis
  .travis.yml
Labels: Devops

#12 Update package.json
  package.json
Labels: Devops

#9 Add antd, CRA configuration overrides for custom ant theme
  README.md
  craco.config.js
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/app/app.container.less
  src/app/app.container.spec.tsx
  src/app/app.container.tsx
  src/app/service-worker.ts
  src/index.tsx
  src/logo.svg
  src/styles/ant-variables.less
  src/styles/index.less
Labels: Engineering, Feature

#17 Initial Docker implementation
  .dockerignore
  .travis.yml
  Dockerfile
  docker-compose.yml
Labels: Devops

#18 Update Readme
  README.md
Labels: Repo

#19 Add mockups
  docs/mockups.pdf
  docs/mockups.xd
Labels: Spec

#21 Create LICENSE
  LICENSE
Labels: Repo

#22 Implement Redux POC
  .gitignore
  package-lock.json
  package.json
  src/app/app.container.tsx
  src/containers/counter/counter.container.tsx
  src/index.tsx
  src/state/counter/counter.actions.ts
  src/state/counter/counter.reducer.ts
  src/state/index.ts
  src/state/utils/dispatch.util.ts
  tsconfig.json
  tslint.json
Labels: Engineering, Open For Suggestions
