Repository decrn/localsurvey, pull requests merged in 2019-02, with the labels that each got.

#36 Update survey form
  src/common/components/status-tag/status-tag.component.tsx
  src/common/mappers/survey-status.mapper.ts
  src/common/types/survey-status.type.ts
  src/common/types/survey.type.ts
  src/containers/homepage/homepage.container.tsx
  src/containers/homepage/survey-list.component.tsx
  src/state/homepage/homepage.reducer.ts
  src/state/state.constants.ts
Labels: Feature

#41 Refactor PageState to generic SurveysState
  src/containers/homepage/homepage.container.tsx
  src/state/index.ts
  src/state/state.constants.ts
  src/state/surveys/surveys.reducer.ts
Labels: Engineering, Open For Suggestions

#38 Add search and status filtering to SurveyList
  .gitignore
  src/common/components/status-tag/status-tag.component.less
  src/common/components/status-tag/status-tag.component.tsx
  src/common/components/survey-table/survey-table.component.less
  src/common/components/survey-table/survey-table.component.tsx
  src/common/mappers/survey-status.mapper.ts
  src/common/utils/date.utils.ts
  src/containers/homepage/homepage.container.tsx
  src/containers/homepage/survey-list.component.tsx
  src/state/state.constants.ts
  src/state/surveys/surveys.actions.ts
  src/state/surveys/surveys.reducer.ts
  tsconfig.json
  tslint.json
Labels: Feature, Open For Suggestions

#45 Change home page styling
  src/containers/homepage/homepage.container.less
  src/containers/homepage/homepage.container.tsx
Labels: Design

#46 Add persistence through LocalStorage API
  package-lock.json
  package.json
  src/declarations.d.ts
  src/index.tsx
  src/state/index.ts
  tsconfig.json
Labels: Engineering, Open For Suggestions

#40 Add a detail page
  package-lock.json
  package.json
  src/app/app.container.tsx
  src/common/components/color-picker/color-picker.component.tsx
  src/common/components/status-tag/status-tag.component.tsx
  src/common/components/survey-form/survey-form.component.less
  src/common/components/survey-form/survey-form.component.tsx
  src/common/components/survey-table/survey-table.component.less
  src/common/components/survey-table/survey-table.component.tsx
  src/common/types/survey.type.ts
  src/containers/detail/branding.form.tsx
  src/containers/detail/detail.container.less
  src/containers/detail/detail.container.tsx
  src/containers/homepage/homepage.container.tsx
  src/layout/admin/admin-layout.container.less
  src/layout/admin/admin-layout.container.tsx
  src/state/state.constants.ts
  src/state/surveys/surveys.actions.ts
  src/state/surveys/surveys.reducer.ts
  src/styles/index.less
Labels: Feature, Open For Suggestions

#53 Add StatusTag tests
  src/common/components/status-tag/status-tag.component.spec.tsx
Labels: Testing

#51 Remove counter component
  src/app/app.container.tsx
  src/containers/counter/counter.container.tsx
  src/state/counter/counter.actions.ts
  src/state/counter/counter.reducer.ts
  src/state/index.ts
Labels: Engineering
